# Rancang Bangun Jaringan Saraf Tiruan untuk Sistem Kendali Lingkungan Termal Climate Chamber

### Program Kecerdasan Buatan untuk membentuk model jaringan saraf tiruan dalam memenuhi Tugas Akhir program studi Teknik Fisika.
### Data di Bulan Maret 2019

In [1]:
# Mengimpor pustaka untuk pengolahan data.
import numpy as np
import pandas as pd

from subprocess import check_output
print(check_output(["ls", "../Data"]).decode("utf8"))

dataDES.xlsx
dataJUN.xlsx
dataMar.xlsx
dataSEP.xlsx
Data Simulasi IESVE (1-60).xlsx
Data Simulasi IESVE (61-80).xlsx
Data Simulasi IESVE (81-100).xlsx
Data Training ANN (1-60).xlsx
Data Training ANN (61-80).xlsx
Data Training ANN (81-100).xlsx
Data Training ANN Gabung (1-100).xlsx
Data Training Musim 1. Mar.xlsx
Data Training Musim 2. Jun.xlsx
Data Training Musim 3. Sep.xlsx
Data Training Musim 4. Des.xlsx

In [2]:
# Mengimpor pustaka untuk visualisasi.
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns

In [3]:
# Memasukkan dataset ke dalam jupyter.
dataMar = pd.read_excel('../Data/dataMar.xlsx')

In [4]:
# Menampilkan 5 data teratas.
dataMar.head()

   No      Time  Heater  AC  DrybulbT  Radiation   AirT     RH   DT
0   1  00:03:00       0   0     24.08        0.0  24.03  70.64  DT1
1   2  00:09:00       0   0     24.08        0.0  24.03  70.72  NaN
2   3  00:15:00       0   0     24.08        0.0  24.04  70.81  NaN
3   4  00:21:00       0   0     24.08        0.0  24.04  70.90  NaN
4   5  00:27:00       0   0     24.08        0.0  24.04  70.99  NaN

In [5]:
# Membuang fitur No, Time dan DT.
dataMar = dataMar.drop(['No','Time','DT'], axis =1)

In [6]:
# Memeriksa persebaran statistik data.
dataMar.describe()

,Heater,AC,DrybulbT,Radiation,AirT,RH
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000
mean,0.600000,9.375000,25.211667,104.668917,24.568788,94.383172
std,0.800067,12.379819,1.464896,172.175583,2.428443,7.556413
min,0.000000,0.000000,22.920000,0.000000,16.000000,70.030000
25%,0.000000,0.000000,23.952500,0.000000,24.010000,90.887500
50%,0.000000,0.000000,25.050000,0.000000,24.755000,98.430000
75%,1.000000,24.000000,26.667500,140.000000,26.000000,99.990000
max,2.000000,30.000000,27.300000,660.271000,30.020000,100.000000

In [7]:
# Memeriksa nilai yang kosong.
dataMar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 6 columns):
Heater       6000 non-null int64
AC           6000 non-null int64
DrybulbT     6000 non-null float64
Radiation    6000 non-null float64
AirT         6000 non-null float64
RH           6000 non-null float64
dtypes: float64(4), int64(2)
memory usage: 281.4 KB

## Klasifikasi menggunakan Multi-Layer Perceptron

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [9]:
# Memisahkan data input dan data target.
x = dataMar[['DrybulbT','Radiation','AirT','RH']] # Data Input
y = dataMar[['Heater','AC']]                      # Data Target

In [10]:
# Variabel untuk pembuatan grafik
DrybulbT  = x['DrybulbT']
Radiation = x['Radiation']
AirT      = x['AirT']
RH        = x['RH']
Heater    = y['Heater']
AC        = y['AC']

In [11]:
# One Hot Encoding
y = pd.get_dummies(y, columns = ['Heater','AC'])

In [12]:
# Memisahkan data pelatihan (training) dan data pengujian (testing).
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=(0.20), random_state=27)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(4800, 4) (1200, 4) (4800, 19) (1200, 19)

In [13]:
# Validasi data telah teracak
y_test.head()

,Heater_0,Heater_1,Heater_2,AC_0,AC_16,AC_17,AC_18,AC_19,AC_20,AC_21,AC_22,AC_23,AC_24,AC_25,AC_26,AC_27,AC_28,AC_29,AC_30
943,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4085,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
283,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4021,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4560,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
x_train_v = x_train.values
x_test_v = x_test.values
y_train_v = y_train.values
y_test_v = y_test.values

In [15]:
# # Mencari jumlah hidden layer dan neuron optimal
# import operator

# def ann(m,n):
#     return MLPClassifier(hidden_layer_sizes=(m,n), max_iter=500, alpha=0.0001, solver='adam', verbose=10,  random_state=21, tol=0.000000001)

# daftar = {}
# for i in range(4,6):
#     for j in range(2,4):
#         model = ann(i,j)
#         model.fit(x_train_v, y_train_v)
#         y_pred = model.predict(x_test_v)
#         accuracy = accuracy_score(y_test_v, y_pred)
#         key = str(i) + ',' + str(j)
#         daftar[key] = accuracy
#         if accuracy >= 50:
#             neuron = {i,j}
#             break
#         else:
#             neuron = max(daftar.items(), key=operator.itemgetter(1))[0]

# print(neuron, daftar)

In [16]:
# Pembuatan model
model_clf = MLPClassifier(activation='relu', hidden_layer_sizes=(100,75,100), max_iter=500, alpha=0.0001,
                     solver='adam', verbose=10,  random_state=21, tol=0.000000001)
# model_clf = MLPClassifier()

In [17]:
model_clf.fit(x_train, y_train)     # Pelatihan model

Iteration 1, loss = inf
Iteration 2, loss = 4.41729991
Iteration 3, loss = 3.51146288
Iteration 4, loss = 3.31710470
Iteration 5, loss = 3.25094962
Iteration 6, loss = 3.18363897
Iteration 7, loss = 3.12424039
Iteration 8, loss = 3.06434373
Iteration 9, loss = 3.01629696
Iteration 10, loss = 2.94993645
Iteration 11, loss = 2.96295798
Iteration 12, loss = 2.90556582
Iteration 13, loss = 2.86063012
Iteration 14, loss = 2.81342865
Iteration 15, loss = 2.81066200
Iteration 16, loss = 2.77941897
Iteration 17, loss = 2.80167566
Iteration 18, loss = 2.73287777
Iteration 19, loss = 2.71650747
Iteration 20, loss = 2.70353573
Iteration 21, loss = 2.69886199
Iteration 22, loss = 2.69151820
Iteration 23, loss = 2.66697348
Iteration 24, loss = 2.63446721
Iteration 25, loss = 2.63798999
Iteration 26, loss = 2.63369145
Iteration 27, loss = 2.60660296
Iteration 28, loss = 2.58529155
Iteration 29, loss = 2.57800180
Iteration 30, loss = 2.58353242
Iteration 31, loss = 2.57575546
Iteration 32, loss = 2.57979802
Iteration 33, loss = 2.55961795
Iteration 34, loss = 2.54877610
Iteration 35, loss = 2.56670583
Iteration 36, loss = 2.52765670
Iteration 37, loss = 2.52159511
Iteration 38, loss = 2.49480048
Iteration 39, loss = 2.48917886
Iteration 40, loss = 2.46808032
Iteration 41, loss = 2.49353111
Iteration 42, loss = 2.47634392
Iteration 43, loss = 2.44727714
Iteration 44, loss = 2.49972481
Iteration 45, loss = 2.49115343
Iteration 46, loss = 2.46041663
Iteration 47, loss = 2.46072537
Iteration 48, loss = 2.43269952
Iteration 49, loss = 2.41483838
Iteration 50, loss = 2.41640999
Iteration 51, loss = 2.40646068
Iteration 52, loss = 2.44480534
Iteration 53, loss = 2.39513834
Iteration 54, loss = 2.39825760
Iteration 55, loss = 2.38845690
Iteration 56, loss = 2.37345534
Iteration 57, loss = 2.36747014
Iteration 58, loss = 2.36111442
Iteration 59, loss = 2.37423458
Iteration 60, loss = 2.36664179
Iteration 61, loss = 2.33449696
Iteration 62, loss = 2.37955452
Iteration 63, loss = 2.36945342
Iteration 64, loss = 2.33206841
Iteration 65, loss = 2.32548912
Iteration 66, loss = 2.30639643
Iteration 67, loss = 2.30957089
Iteration 68, loss = 2.33089207
Iteration 69, loss = 2.31807074
Iteration 70, loss = 2.30211207
Iteration 71, loss = 2.31485558
Iteration 72, loss = 2.32134401
Iteration 73, loss = 2.31534513
Iteration 74, loss = 2.32350915
Iteration 75, loss = 2.30417171
Iteration 76, loss = 2.30314791
Iteration 77, loss = 2.29979039
Iteration 78, loss = 2.28770101
Iteration 79, loss = 2.30330221
Iteration 80, loss = 2.28383841
Iteration 81, loss = 2.25262561
Iteration 82, loss = 2.27945195
Iteration 83, loss = 2.26331533
Iteration 84, loss = 2.24609043
Iteration 85, loss = 2.24188008
Iteration 86, loss = 2.27612019
Iteration 87, loss = 2.25695564
Iteration 88, loss = 2.25512024
Iteration 89, loss = 2.24630970
Iteration 90, loss = 2.26727716
Iteration 91, loss = 2.25198059
Iteration 92, loss = 2.21181926
Iteration 93, loss = 2.21109946
Iteration 94, loss = 2.23887493
Iteration 95, loss = 2.21716025
Iteration 96, loss = 2.23908954
Iteration 97, loss = 2.23571056
Iteration 98, loss = 2.24079113
Iteration 99, loss = 2.21001246
Iteration 100, loss = 2.20597432
Iteration 101, loss = 2.20357358
Iteration 102, loss = 2.18897602
Iteration 103, loss = 2.19157551
Iteration 104, loss = 2.20911127
Iteration 105, loss = 2.20558531
Iteration 106, loss = 2.19015381
Iteration 107, loss = 2.16652602
Iteration 108, loss = 2.17506102
Iteration 109, loss = 2.18797799
Iteration 110, loss = 2.16176243
Iteration 111, loss = 2.15660235
Iteration 112, loss = 2.13936475
Iteration 113, loss = 2.16762644
Iteration 114, loss = 2.21968141
Iteration 115, loss = 2.17407377
Iteration 116, loss = 2.15045056
Iteration 117, loss = 2.12519590
Iteration 118, loss = 2.15397460
Iteration 119, loss = 2.17979833
Iteration 120, loss = 2.13966055
Iteration 121, loss = 2.12722863
Iteration 122, loss = 2.14200341
Iteration 123, loss = 2.13758772
Iteration 124, loss = 2.17279443
Iteration 125, loss = 2.14809224
Iteration 126, loss = 2.12217940
Iteration 127, loss = 2.12264854
Iteration 128, loss = 2.15465460
Iteration 129, loss = 2.11749948
Iteration 130, loss = 2.10285502
Iteration 131, loss = 2.13880771
Iteration 132, loss = 2.11879641
Iteration 133, loss = 2.12159211
Iteration 134, loss = 2.07900325
Iteration 135, loss = 2.09415827
Iteration 136, loss = 2.07920162
Iteration 137, loss = 2.07387322
Iteration 138, loss = 2.06354198
Iteration 139, loss = 2.05794732
Iteration 140, loss = 2.10777619
Iteration 141, loss = 2.10694533
Iteration 142, loss = 2.06908958
Iteration 143, loss = 2.05309499
Iteration 144, loss = 2.04275195
Iteration 145, loss = 2.04474373
Iteration 146, loss = 2.05635053
Iteration 147, loss = 2.05304266
Iteration 148, loss = 2.03070360
Iteration 149, loss = 2.09225738
Iteration 150, loss = 2.09008871
Iteration 151, loss = 2.06890991
Iteration 152, loss = 2.03977984
Iteration 153, loss = 2.05036874
Iteration 154, loss = 2.05968479
Iteration 155, loss = 2.06325171
Iteration 156, loss = 2.05253139
Iteration 157, loss = 2.00528617
Iteration 158, loss = 1.98489084
Iteration 159, loss = 2.02299016
Iteration 160, loss = 2.04569168
Iteration 161, loss = 1.99930426
Iteration 162, loss = 1.99780737
Iteration 163, loss = 2.02826137
Iteration 164, loss = 2.01189111
Iteration 165, loss = 1.98491733
Iteration 166, loss = 2.02004236
Iteration 167, loss = 2.01035409
Iteration 168, loss = 1.98456216
Iteration 169, loss = 2.05031259
Iteration 170, loss = 2.00952789
Iteration 171, loss = 1.96570824
Iteration 172, loss = 1.94105754
Iteration 173, loss = 1.98473495
Iteration 174, loss = 1.95069128
Iteration 175, loss = 1.96962199
Iteration 176, loss = 2.01353785
Iteration 177, loss = 1.99504416
Iteration 178, loss = 1.96745096
Iteration 179, loss = 1.94357826
Iteration 180, loss = 1.93138361
Iteration 181, loss = 1.93430578
Iteration 182, loss = 1.92993271
Iteration 183, loss = 1.89764043
Iteration 184, loss = 1.90135646
Iteration 185, loss = 1.99007379
Iteration 186, loss = 2.06714351
Iteration 187, loss = 1.98917518
Iteration 188, loss = 1.92314290
Iteration 189, loss = 1.89656173
Iteration 190, loss = 1.90415265
Iteration 191, loss = 1.93132687
Iteration 192, loss = 1.95879769
Iteration 193, loss = 1.92025858
Iteration 194, loss = 1.92129795
Iteration 195, loss = 1.89067485
Iteration 196, loss = 1.86575061
Iteration 197, loss = 1.84849420
Iteration 198, loss = 1.88164219
Iteration 199, loss = 1.92526694
Iteration 200, loss = 1.86291106
Iteration 201, loss = 1.86217666
Iteration 202, loss = 1.88090160
Iteration 203, loss = 1.88361940
Iteration 204, loss = 1.87857597
Iteration 205, loss = 1.87439501
Iteration 206, loss = 1.86805748
Iteration 207, loss = 1.83851552
Iteration 208, loss = 1.83365872
Iteration 209, loss = 1.85174976
Iteration 210, loss = 1.86921353
Iteration 211, loss = 1.87323962
Iteration 212, loss = 1.88772303
Iteration 213, loss = 1.89292958
Iteration 214, loss = 1.84160981
Iteration 215, loss = 1.85700156
Iteration 216, loss = 1.85147743
Iteration 217, loss = 1.81324782
Iteration 218, loss = 1.81926794
Iteration 219, loss = 1.82067479
Iteration 220, loss = 1.83775101
Iteration 221, loss = 1.86053683
Iteration 222, loss = 1.82448033
Iteration 223, loss = 1.97962236
Iteration 224, loss = 1.87823566
Iteration 225, loss = 1.80305886
Iteration 226, loss = 1.82712429
Iteration 227, loss = 1.81317218
Iteration 228, loss = 1.83285107
Iteration 229, loss = 1.85604298
Iteration 230, loss = 1.80664531
Iteration 231, loss = 1.77791520
Iteration 232, loss = 1.82384300
Iteration 233, loss = 1.79473841
Iteration 234, loss = 1.76609965
Iteration 235, loss = 1.79413717
Iteration 236, loss = 1.81237060
Iteration 237, loss = 1.84493931
Iteration 238, loss = 1.79750806
Iteration 239, loss = 1.85568798
Iteration 240, loss = 1.89094198
Iteration 241, loss = 1.84034627
Iteration 242, loss = 1.74771391
Iteration 243, loss = 1.76336342
Iteration 244, loss = 1.76911476
Iteration 245, loss = 1.79908049
Iteration 246, loss = 1.75895202
Iteration 247, loss = 1.74468514
Iteration 248, loss = 1.76101333
Iteration 249, loss = 1.80585771
Iteration 250, loss = 1.74227464
Iteration 251, loss = 1.72997387
Iteration 252, loss = 1.74454010

Iteration 253, loss = 1.77164775
Iteration 254, loss = 1.74572554
Iteration 255, loss = 1.75883539
Iteration 256, loss = 1.75971113
Iteration 257, loss = 1.77178545
Iteration 258, loss = 1.73273549
Iteration 259, loss = 1.77463806
Iteration 260, loss = 1.77635853
Iteration 261, loss = 1.73906147
Iteration 262, loss = 1.73252771
Training loss did not improve more than tol=0.000000 for 10 consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 75, 100), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=21, shuffle=True, solver='adam', tol=1e-09,
              validation_fraction=0.1, verbose=10, warm_start=False)

In [18]:
y_pred = model_clf.predict(x_test)  # Prediksi output
accuracy_score(y_test, y_pred)      # Menampilkan akurasi prediksi

0.44583333333333336

In [72]:
# y_pred = pd.DataFrame({"Heater":y_pred[:,0:3], "AC":y_pred[:,3:]})
# def get_animal(row):
#     for c in animals.columns:
#         if row[c]==1:
#             return c

In [20]:
# Menampilkan confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

ValueError: multilabel-indicator is not supported

# Visualisasi

In [ ]:
# plot a line, a perfit predict would all fall on this line
plt.subplot(2, 1, 1)
plt.title('Grafik AirT terhadap AC dan Heater')
plt.plot(AirT, AC, '.')
plt.plot(AirT, AC, 'r.')
plt.ylabel('AC')

plt.subplot(2, 1, 2)
plt.plot(AirT, Heater, '.')
plt.plot(AirT, Heater, 'r.')
plt.xlabel('Airt')
plt.ylabel('Heater')

plt.show()

In [ ]:
plt.subplot(2, 1, 1)
plt.title('Grafik AC terhadap AirT dan RH')
plt.plot(x_test.values[:,1], y_test.values[:,0], '.')
plt.plot(x_test.values[:,1], y_pred[:,0], 'r.')
plt.ylabel('AirT')

plt.subplot(2, 1, 2)
plt.plot(x_test.values[:,1], y_test.values[:,1], '.')
plt.plot(x_test.values[:,1], y_pred[:,1], 'r.')
plt.xlabel('AC')
plt.ylabel('RH')

plt.show()

In [ ]:
plt.subplot(2, 1, 1)
plt.title('Grafik DrybulbT terhadap AirT dan RH')
plt.plot(x_test.values[:,2], y_test.values[:,0], '.')
plt.plot(x_test.values[:,2], y_pred[:,0], 'r.')
plt.ylabel('AirT')

plt.subplot(2, 1, 2)
plt.plot(x_test.values[:,2], y_test.values[:,1], '.')
plt.plot(x_test.values[:,2], y_pred[:,1], 'r.')
plt.xlabel('DrybulbT')
plt.ylabel('RH')

plt.show()

In [ ]:
plt.subplot(2, 1, 1)
plt.title('Grafik Radiation terhadap AirT dan RH')
plt.plot(x_test.values[:,3], y_test.values[:,0], '.')
plt.plot(x_test.values[:,3], y_pred[:,0], 'r.')
plt.ylabel('AirT')

plt.subplot(2, 1, 2)
plt.plot(x_test.values[:,3], y_test.values[:,1], '.')
plt.plot(x_test.values[:,3], y_pred[:,1], 'r.')
plt.xlabel('Radiation')
plt.ylabel('RH')

plt.show()